config/routes.rb
Rails.application.routes.draw do
  resources :gossip do
    resources :comment
  end
  resources :gossip
  resources :user
  resources :welcome
  resources :city
  resources :comment
  resources :session, only: [:new, :create, :destroy]
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  root 'gossip#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :imageable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :intertags
  has_many :comments
  has_many :likes, as: :imageable
  has_many :tags, through: :intertags
  validates :content, presence: true
  validates :title, presence: true, length: {minimum: 3, maximum: 14}
end

app/models/intertag.rb
# Correspond à Join Tag et Gossip
class Intertag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :intertags
  has_many :gossips, through: :intertags
  has_many :users, through: :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :tags, through: :gossips
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ } #/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :password, presence: true
  has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def index
  end

  def show
    def show
      @current_city = City.find(params[:id].to_i)
    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    @current_gossip = Gossip.find(params[:gossip_id].to_i)
    @comment = Comment.new(
      'user_id' => User.all.sample.id,
      'gossip_id' => @current_gossip.id,
      'content' => params[:content]
    )
    puts params
    if @comment.save
      redirect_to gossip_path(@current_gossip)
    else
      render :new
    end
  end

  def edit
    @current_gossip = Gossip.find(params[:gossip_id].to_i)
    @current_comment = @current_gossip.comments.find(params[:id].to_i)
  end

  def update
    @current_gossip = Gossip.find(params[:gossip_id].to_i)
    @current_comment = @current_gossip.comments.find(params[:id].to_i)
    comment_params = params.permit(:content)
    if @current_comment.update(comment_params)
      redirect_to gossip_path(@current_gossip)#(:update_success)
    else
      redirect_to gossip_path()#(:update_failed)
    end
  end

  def destroy
    @current_gossip = Gossip.find(params[:gossip_id].to_i)
    @current_comment = @current_gossip.comments.find(params[:id].to_i)
    if @current_comment.destroy
      redirect_to gossip_path(@current_gossip)
    else
      redirect_to root_path()
    end
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  def index
    @all_gossips = Gossip.all
    @all_users = User.all
  end

  def new
    @gossip = Gossip.new
  end
  
  def create
    @gossip = Gossip.new('user_id' => User.all.sample.id,
                   'title' => params[:title],
                   'content' => params[:content])
    #@gossip.user = User.find_by(id: session[:user_id])
    if @gossip.save
      redirect_to root_path(success: true)
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id].to_i)
  end

  def show
    @current_gossip = Gossip.find(params[:id].to_i)
  end

  def update
      @gossip = Gossip.find(params[:id])
      if @gossip.update('user_id' => User.all.sample.id,'title' => params[:title],'content' => params[:content])
        redirect_to @gossip
      else
        render :edit
      end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def contact
  end

  def team
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  
  def index
  end

  def create
    @user = User.new(
                   'first_name' => params[:first_name],
                   'last_name' => params[:last_name],
                   'email' => params[:email],
                   'password' => params[:password],
                   'city_id' =>  User.all.sample.id           
                   )
                   if @user.save
      @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path(success: true)
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
    @current_user = User.find(params[:id].to_i)
  end

  def update
  end

  def destroy
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
      def current_user_name
        User.find_by(id: session[:user_id]).first_name
      end
    
      def logged_in?
        session[:user_id].present?
      end
    
      def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/comment/edit.html.erb
<h1>Editer le commentaire</h1>

<div>
  <%= form_tag url_for(action: 'update'), method: "patch" do %>
    <br /> <br />
    <%= label_tag 'Content' %>
    <%= text_area_tag 'content', @current_comment.content %>
    <br /> <br />
    <br /> <br />
    <%= submit_tag "Edit Commentaire" %>
  <% end %>
</div>

app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/comment/new.html.erb
<body data-turbo="false">
  <%= yield %> 

<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>
<% if @comment.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <%= form_tag url_for(controller: 'comment', action: 'create'), method: "post" do %>
    <%= hidden_field_tag 'gossip_id', @current_gossip.id %>
    <%= label_tag 'Content' %>
    <%= text_area_tag 'content', @comment.content %>
    <%= submit_tag "Create Comment" %>
  <% end %>
</div>
</body>

app/views/comment/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

app/views/comment/update.html.erb
<h1>Comment#update</h1>
<p>Find me in app/views/comment/update.html.erb</p>

app/views/gossip/create.html.erb
<h1>Gossip#create</h1>
<p>Find me in app/views/gossip/create.html.erb</p>

app/views/gossip/destroy.html.erb
<h1>Gossip#destroy</h1>
<p>Find me in app/views/gossip/destroy.html.erb</p>

app/views/gossip/edit.html.erb
<body data-turbo="false">
  <%= yield %> 

<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <%= form_tag url_for(action: 'update'), method: "patch" do %>
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @gossip.title %>
    <br /> <br />
    <%= label_tag 'Content' %>
    <%= text_area_tag 'content', @gossip.content %>
    <br /> <br />
    <br /> <br />
    <%= submit_tag "Update Post" %>
  <% end %>
</div>
</body>

app/views/gossip/index.html.erb
<% if params[:success] %>
  <div class="alert alert-success" role="alert">
    Votre potin a été créé avec succès !
  </div>
<% end %>
<% if params[:edit_success] %>
  <div class="alert alert-success" role="alert">
    Votre potin a été modifie avec succès !
  </div>
<% end %>
<% if params[:destroy_success] %>
  <div class="alert alert-success" role="alert">
    Votre potin a été supprime avec succès !
  </div>
<% end %>

<% if params[:update_failed] || params[:destroy_failed] %>
  <div class="alert alert-danger" role="alert">
    Ce n'est pas votre potin !
  </div>
<% end %>

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Bienvenue 
    <% if logged_in? %>
      <%= User.find_by(id: session[:user_id]).first_name %> !
    <% else %>
      !
    <% end %></h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><%= link_to "Cliquez ici pour creer votre propre potin.", new_gossip_path, :class => "btn btn-dark"%></p>



  </div>
</div>

<div class="container">

<div class="row">
<%@all_gossips.each do |elem|%>
  <div class="col-md-2">
    <div class="card mb-2">
      <div class="card-body">
        <h5 class="card-title"><%= elem.title %></h5>
        <p class="card-text"><small class="text-muted">Posted by <%= link_to elem.user.first_name, user_path(elem.user) %></small></p>
        <%= link_to "Read more", gossip_path(elem), class: "btn btn-dark" %>
        Commentaires : <%=elem.comments.count%>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/gossip/new.html.erb
<body data-turbo="false">
  <%= yield %> 

<h1>Gossip#new</h1>
<p>Find me in app/views/gossip/new.html.erb</p>
<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @gossip.title %>
    <br /> <br />
    <%= label_tag 'Content' %>
    <%= text_area_tag 'content', @gossip.content %>
    <br /> <br />
    <br /> <br />
    <%= submit_tag "Create Post" %>
  <% end %>
</div>
</body>

app/views/gossip/show.html.erb
<div class="container text-center justify-content-center">

<h1>Bienvenue sur la page Gossip n°<%=@current_gossip.id %></h1>

<p>Auteur du Potin : <%= link_to @current_gossip.user.first_name, user_path(@current_gossip.user.id), :class => "nav-link"%> </p>
<p>Titre du Potin : <%=@current_gossip.title %></p>
<p>Date de creation du Potin : <%=@current_gossip.created_at %></p>
<p>Potin : <%=@current_gossip.content %></p>

<%= link_to "edit your potin", edit_gossip_path(@current_gossip.id), :class => "nav-link"%> 
</div>
<%= button_to "Delete", gossip_path(@current_gossip), method: :delete, class: "btn btn-danger" %>

<%= button_to "Edit", edit_gossip_path(@current_gossip.id), method: :get, class: "btn btn-secondary" %>

<%= button_to "Comment", new_comment_path(gossip_id: @current_gossip.id), method: :get, class: "btn btn-secondary" %>

Commentaires (<%=@current_gossip.comments.count%>) :
<div class="container text-center">
    <%@current_gossip.comments.each do |elem|%>
        <p><strong> <%= elem.user.first_name%></strong> :
        <%= elem.content%>
        <small><%= button_to "Supprimer", gossip_comment_path(@current_gossip.id, elem.id), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: "btn btn-danger" %></small>
         <%= link_to "Editer", edit_gossip_comment_path(@current_gossip.id, elem.id), :class => "btn btn-danger"%>
         </p>
        <%end%>
</div>
<div>
  <%= form_with url: url_for(controller: 'comment', action: 'create', gossip_id: @current_gossip.id) do |form| %>
    <%= form.label :commentaire %>
    <%= form.text_area :content %>

    <%= form.submit %>
  <% end %>
</div>

app/views/gossip/update.html.erb
<h1>Gossip#update</h1>
<p>Find me in app/views/gossip/update.html.erb</p>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<body data-turbo="false">
  <%= yield %> 

<% if @user.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à créer le user pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <%= label_tag 'first_name' %>
    <%= text_field_tag 'first_name', @user.first_name %>
    <br /> <br />
    <%= label_tag 'last_name' %>
    <%= text_area_tag 'last_name', @user.last_name %>
    <br /> <br />
    <%= label_tag 'email' %>
    <%= text_area_tag 'email', @user.email %>
    <%= label_tag 'password' %>
    <%= password_field_tag 'password', @user.password %>
    <%= label_tag 'password' %>
    <%= submit_tag "Create Post" %>
  <% end %>
</div>
</body>

app/views/user/show.html.erb
<div class="container text-center justify-content-center">

<h1>Bienvenu sur le profil de <%= @current_user.first_name %></h1>

<p>Prénom : <%= @current_user.first_name %> </p>
<p>Nom : <%= @current_user.last_name %>  </p>
<p>Âge : <%= @current_user.age %>  </p>
<p>Email : <%= @current_user.email %>  </p>
<p>Habite : <%= link_to @current_user.city.name, city_path(@current_user.city.id), :class => "nav-link"%>  </p>
<p>Description : <%= @current_user.description %>  </p>
<p>Find me in app/views/static/index.html.erb</p>

</div>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>