config/routes.rb
Rails.application.routes.draw do
  resources :gossip do
    resources :comment
  end
  resources :gossip
  resources :user
  resources :welcome
  resources :city
  resources :comment
  resources :session, only: [:new, :create, :destroy]
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  root 'gossip#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :imageable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :intertags
  has_many :comments
  has_many :likes, as: :imageable
  has_many :tags, through: :intertags
  validates :content, presence: true
  validates :title, presence: true, length: {minimum: 3, maximum: 14}
end

app/models/intertag.rb
# Correspond à Join Tag et Gossip
class Intertag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :intertags
  has_many :gossips, through: :intertags
  has_many :users, through: :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :tags, through: :gossips
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ } #/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :password, presence: true
  has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def index
  end

  def show
    def show
      @current_city = City.find(params[:id].to_i)
    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  
  def index
  end

  def create
    @user = User.new(
                   'first_name' => params[:first_name],
                   'last_name' => params[:last_name],
                   'email' => params[:email],
                   'password' => params[:password],
                   'city_id' =>  User.all.sample.id           
                   )
                   if @user.save
      @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path(success: true)
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
    @current_user = User.find(params[:id].to_i)
  end

  def update
  end

  def destroy
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
      def current_user_name
        User.find_by(id: session[:user_id]).first_name
      end
    
      def logged_in?
        session[:user_id].present?
      end
    
      def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potins</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Team", team_path, :class => "nav-link" %>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item">
              <%= button_to "Deconnexion", session_path(session.id), method: :delete, :class => "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Connexion", new_session_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Inscription", new_user_path, :class => "nav-link"%>
            </li>
          <% end %></h1>
        </ul>
    </nav>
  </header>

    <%= yield %>

  </body>
</html>

app/views/team/team.html.erb
<h2>Bienvenue <%= User.find_by(id: session[:user_id]).first_name %> !</h2>